// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    channels,
    channelSnippets,
    channelThumbnails,
    channelContentDetails,
    channelStatistics,
    channelStatuses,
    videos,
    videoSnippets,
    videoThumbnails,
    videoContentDetails,
    videoStatuses,
    videoStatistics,
    videoProgress,
    playlists,
    playlistSnippets,
    playlistThumbnails,
    playlistContentDetails,
    playlistVsVideos,
    channelSearches,
    channelSearchVsChannels,
    videoSearches,
    videoSearchVsVideos,
    collections,
    series,
    seriesVsVideos,
    channelsIndexETag,
    videosIndexETag,
    playlistIndexETag,
    channelSearchesIndexQuery,
    videoSearchesIndexQuery,
  ];
  late final Shape0 channels = Shape0(
    source: i0.VersionedTable(
      entityName: 'channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 channelSnippets = Shape1(
    source: i0.VersionedTable(
      entityName: 'channel_snippets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_5, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 channelThumbnails = Shape2(
    source: i0.VersionedTable(
      entityName: 'channel_thumbnails',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_5, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 channelContentDetails = Shape3(
    source: i0.VersionedTable(
      entityName: 'channel_content_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_5, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 channelStatistics = Shape4(
    source: i0.VersionedTable(
      entityName: 'channel_statistics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_5, _column_13, _column_14, _column_15, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 channelStatuses = Shape5(
    source: i0.VersionedTable(
      entityName: 'channel_statuses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_5, _column_17, _column_18, _column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 videos = Shape6(
    source: i0.VersionedTable(
      entityName: 'videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 videoSnippets = Shape7(
    source: i0.VersionedTable(
      entityName: 'video_snippets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_22, _column_23, _column_6, _column_7, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 videoThumbnails = Shape8(
    source: i0.VersionedTable(
      entityName: 'video_thumbnails',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_22,
        _column_8,
        _column_9,
        _column_10,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 videoContentDetails = Shape9(
    source: i0.VersionedTable(
      entityName: 'video_content_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_22,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 videoStatuses = Shape10(
    source: i0.VersionedTable(
      entityName: 'video_statuses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_22,
        _column_33,
        _column_17,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 videoStatistics = Shape11(
    source: i0.VersionedTable(
      entityName: 'video_statistics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_22,
        _column_13,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 videoProgress = Shape12(
    source: i0.VersionedTable(
      entityName: 'video_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_22, _column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 playlists = Shape13(
    source: i0.VersionedTable(
      entityName: 'playlists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_21,
        _column_44,
        _column_45,
        _column_46,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 playlistSnippets = Shape14(
    source: i0.VersionedTable(
      entityName: 'playlist_snippets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_47,
        _column_23,
        _column_6,
        _column_7,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 playlistThumbnails = Shape15(
    source: i0.VersionedTable(
      entityName: 'playlist_thumbnails',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_47,
        _column_8,
        _column_9,
        _column_10,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 playlistContentDetails = Shape16(
    source: i0.VersionedTable(
      entityName: 'playlist_content_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_47, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 playlistVsVideos = Shape17(
    source: i0.VersionedTable(
      entityName: 'playlist_vs_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(playlist_id, video_id)'],
      columns: [_column_49, _column_50, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 channelSearches = Shape18(
    source: i0.VersionedTable(
      entityName: 'channel_searches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_51, _column_52],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 channelSearchVsChannels = Shape19(
    source: i0.VersionedTable(
      entityName: 'channel_search_vs_channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(search_id, channel_id)'],
      columns: [_column_53, _column_21, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 videoSearches = Shape18(
    source: i0.VersionedTable(
      entityName: 'video_searches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_51, _column_52],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 videoSearchVsVideos = Shape20(
    source: i0.VersionedTable(
      entityName: 'video_search_vs_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(search_id, video_id)'],
      columns: [_column_54, _column_50, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 collections = Shape21(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_51,
        _column_55,
        _column_45,
        _column_56,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 series = Shape22(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_51,
        _column_57,
        _column_58,
        _column_56,
        _column_7,
        _column_59,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 seriesVsVideos = Shape23(
    source: i0.VersionedTable(
      entityName: 'series_vs_videos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id, video_id)'],
      columns: [_column_60, _column_50, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index channelsIndexETag = i1.Index(
    'ChannelsIndexETag',
    'CREATE INDEX ChannelsIndexETag ON channels (etag)',
  );
  final i1.Index videosIndexETag = i1.Index(
    'VideosIndexETag',
    'CREATE INDEX VideosIndexETag ON videos (etag)',
  );
  final i1.Index playlistIndexETag = i1.Index(
    'PlaylistIndexETag',
    'CREATE INDEX PlaylistIndexETag ON playlists (etag)',
  );
  final i1.Index channelSearchesIndexQuery = i1.Index(
    'ChannelSearchesIndexQuery',
    'CREATE INDEX ChannelSearchesIndexQuery ON channel_searches ("query")',
  );
  final i1.Index videoSearchesIndexQuery = i1.Index(
    'VideoSearchesIndexQuery',
    'CREATE INDEX VideoSearchesIndexQuery ON video_searches ("query")',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etag =>
      columnsByName['etag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setag =>
      columnsByName['setag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'created_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_1(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'updated_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'etag',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'setag',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES channels(id)',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultUrl =>
      columnsByName['default_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediumUrl =>
      columnsByName['medium_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get highUrl =>
      columnsByName['high_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'medium_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'high_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get likesPlaylist =>
      columnsByName['likes_playlist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadPlaylist =>
      columnsByName['upload_playlist']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'likes_playlist',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'upload_playlist',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get viewCount =>
      columnsByName['view_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subscriberCount =>
      columnsByName['subscriber_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hiddenSubscriberCount =>
      columnsByName['hidden_subscriber_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get videoCount =>
      columnsByName['video_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'view_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'subscriber_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hidden_subscriber_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (hidden_subscriber_count IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'video_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacyStatus =>
      columnsByName['privacy_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isLinked =>
      columnsByName['is_linked']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get longUploadsStatus =>
      columnsByName['long_uploads_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get madeForKids =>
      columnsByName['made_for_kids']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'privacy_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_linked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_linked IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'long_uploads_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'made_for_kids',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (made_for_kids IN (0, 1))',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get etag =>
      columnsByName['etag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get setag =>
      columnsByName['setag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'channel_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES channels(id)',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publishedAt =>
      columnsByName['published_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelTitle =>
      columnsByName['channel_title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES videos(id)',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'published_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'channel_title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultUrl =>
      columnsByName['default_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediumUrl =>
      columnsByName['medium_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get highUrl =>
      columnsByName['high_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get standardUrl =>
      columnsByName['standard_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get maxresUrl =>
      columnsByName['maxres_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'standard_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maxres_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get duration =>
      columnsByName['duration']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dimension =>
      columnsByName['dimension']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get definition =>
      columnsByName['definition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get caption =>
      columnsByName['caption']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get licensedContent =>
      columnsByName['licensed_content']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get projection =>
      columnsByName['projection']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'duration',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dimension',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'definition',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'caption',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'licensed_content',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (licensed_content IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'projection',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get uploadStatus =>
      columnsByName['upload_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacyStatus =>
      columnsByName['privacy_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get license =>
      columnsByName['license']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get embeddable =>
      columnsByName['embeddable']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get publicStatsViewable =>
      columnsByName['public_stats_viewable']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get madeForKids =>
      columnsByName['made_for_kids']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'upload_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'license',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'embeddable',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (embeddable IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'public_stats_viewable',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (public_stats_viewable IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'made_for_kids',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (made_for_kids IN (0, 1))',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get viewCount =>
      columnsByName['view_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get likeCount =>
      columnsByName['like_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dislikeCount =>
      columnsByName['dislike_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get favoriteCount =>
      columnsByName['favorite_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get commentCount =>
      columnsByName['comment_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'like_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dislike_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'favorite_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'comment_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get watchPosition =>
      columnsByName['watch_position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isFinished =>
      columnsByName['is_finished']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'watch_position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_finished',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_finished IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get etag =>
      columnsByName['etag']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'etag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publishedAt =>
      columnsByName['published_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelTitle =>
      columnsByName['channel_title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES playlists(id)',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultUrl =>
      columnsByName['default_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediumUrl =>
      columnsByName['medium_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get highUrl =>
      columnsByName['high_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get standardUrl =>
      columnsByName['standard_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get maxresUrl =>
      columnsByName['maxres_url']! as i1.GeneratedColumn<String>;
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get itemCount =>
      columnsByName['item_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'item_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES playlists(id)',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'video_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES videos(id)',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get query =>
      columnsByName['query']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'query',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get searchId =>
      columnsByName['search_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'search_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES channel_searches(id)',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get searchId =>
      columnsByName['search_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'search_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES video_searches(id)',
    );

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isSystem =>
      columnsByName['is_system']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_system',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_system IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get coverVideoId =>
      columnsByName['cover_video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dataHash =>
      columnsByName['data_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'collection_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES collections(id)',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_video_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES videos(id)',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'data_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get videoId =>
      columnsByName['video_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'series_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES series(id)',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
